### ISSUE TITLE
[FEATURE] - (NodeJs) - Add new parameter in additionalData interface

### ISSUE THREAD

**Issue by marlonsousasonae** [Adyen/adyen-node-api-library#1022]
**Is your feature request related to a problem? Please describe.**
I'm using the RealTimeAccountUpdater feature, but I didn't find the parameter realtimeAccountUpdaterStatus in Adyen library.

...adyen-node-api-library/src/typings/notification/additionalData.ts

**Describe the solution you'd like**
It's possible added this parameter in additionalData interface?

**Comment by jillingk** [comment]
Hey @marlonsousasonae,

Thanks for reaching out to us with this issue. I see that we indeed do not have this parameter in the additionalData class, next to a lot of other parameters as well. It seems like we should probably come up with some good way to add all of these parameters at once. Let me discuss this and I'll try to come back to you with a solution asap!

Best, Jilling
Adyen
