### ISSUE TITLE
[BUG] BarcodeValue field in OutputBarcode

### ISSUE THREAD

**Issue by navro** [Adyen/adyen-node-api-library#1048]
OutputBarcode should have a field called `BarcodeValue`. See the docs: 
https://docs.adyen.com/point-of-sale/print-data#print-qr-code

In this library, the field is instead named `Value`. This makes the terminal respond
```
    PrintResponse {
      DocumentQualifier: 'Document',
      Response: Response {
        AdditionalResponse: 'errors=At%20SaleToPOIRequest.PrintRequest.PrintOutput.OutputContent.OutputBarcode%2c%20field%20BarcodeValue%3a%20Missing&warnings=At%20SaleToPOIRequest.PrintRequest.PrintOutput.OutputContent.OutputBarcode%2c%20field%20%27Value%27%3a%20Unexpected',
        ErrorCondition: 'MessageFormat',
        Result: 'Failure'
      }
    }
```

**Comment by jillingk** [comment]
Hi @navro,

Thanks for reaching out to us with this issue. I created a quick PR to address this! Let me know if I can help you with anything else. 

Best, Jilling
Adyen

**Comment by navro** [comment]
Thanks for the super quick fix! 🌟
