### ISSUE TITLE
[FEATURE] Adding enum for Donations webhook event code

### ISSUE THREAD

**Issue by SamySam2099** [Adyen/adyen-node-api-library#1085]
### **Is your feature request related to a problem? Please describe.**

I have an issue with consuming the donations webhook. I am expecting `NotificationRequestItem.EventCodeEnum.Donation` as an event code, but Donation is not an implemented enum in that namespace.

### **Describe the solution you'd like**

Donation enum to be added to`typings/notification/notificationRequestItem`.

### **Describe alternatives you've considered**
Trying to extend the current namespace but I am having issues with that and I think it's an anti-pattern solution for me to implement.

**Comment by jillingk** [comment]
Hi @SamySam2099,

Thanks for reaching out to us with this issue. Indeed it seemed this enum value was missing, I opened a quick PR to address this.

Best, 
Jilling
Adyen
