### ISSUE TITLE
[FEATURE] Can I use this library in react-native, my app want to call api to Adyen terminal?

### ISSUE THREAD

**Issue by hoatenhu** [Adyen/adyen-node-api-library#1108]
I am trying to create an API to call Terminal by myself, but I have spent a lot of time and still cannot make the call. I think this library is quite suitable, but I don't know if it can be integrated into my React Native app and how to integrate it. Please help me.

**Comment by jillingk** [comment]
Hi @hoatenhu,

Thanks a lot for reaching out to us. If you want to know how to set up an API integration with adyen in general using React I would recommend taking a look at our react example integration [here](https://github.com/adyen-examples/adyen-react-online-payments). It showcases a generic store integration with our API in react, using our libraries. 

For documentation on terminal integration in node specifically I would recommend taking a look [here](https://docs.adyen.com/point-of-sale/design-your-integration/choose-your-architecture/local/protect-with-library?tab=node_4#use-the-node-library). There is some code snippets there to integrate with the local terminal API using our node library (the cloud integration is very similar).

Hope this helps! If there is anything along the way that you're not sure about or if you're stuck on anything, be sure to let us know.

Best, Jilling
Adyen

**Comment by brianjd** [comment]
Hi @jillingk ,

The example you link to is for the cloud integration via a backend API.  The issue there is that it prevents offline card processing.  Is there any plan to have this library support React Native directly (https://github.com/Adyen/adyen-react-native/issues/220)?
