### ISSUE TITLE
Can I set a comission from each transaction ?

### ISSUE THREAD

**Issue by pullmann4rent** [Adyen/adyen-node-api-library#1150]
Hello people,

when a transaction is in process can I get a comission ? 

exp:

I have a Company SHOP.

Customer A buys anything (send a transaction) to Customer B. can I intercept 2% of the whole transaction and get the 2% to my company SHOP adyen acc and the other 98% goes to customer B?

**Comment by wboereboom** [comment]
Hi @pullmann4rent ,

Thanks for asking your question.
For all questions on our product offering I'd like to refer to [docs.adyen.com ](https://docs.adyen.com/) and [help.adyen.com](https://help.adyen.com/). 

If you have any additional questions feel free to reach out to our Tech support

Kind Regards,
Wouter
Adyen
