### ISSUE TITLE
[BUG] getAllPaymentMethods() is not properly deserialized

### ISSUE THREAD

**Issue by GarettRogers** [Adyen/adyen-node-api-library#1174]
**Describe the bug**
When calling the getAllPaymentMethods function in the Management API, the response includes an array of empty payment method objects.  It appears that the deserialization of the payment methods that is returned from the API is not considering the type in the response data.

**To Reproduce**
Call getAllPaymentMethods(merchantId) with the latest version (13.1.3)

**Expected behavior**
An array of payment methods, including payment method details, should be returned

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 16.16.0
 - NPM Version: 8.11.0

**Comment by jillingk** [comment]
Hi @GarettRogers,

Massive apology for the late response. This issue was indeed persistent throughout all of our libraries, but has been fixed now! Let us know if you run into anything else.

Best, Jilling
Adyen
