### ISSUE TITLE
[BUG] Requesting ForceEntryMode fails beacuse of incorrect serialization

### ISSUE THREAD

**Issue by Meisolsson** [Adyen/adyen-node-api-library#1184]
**Describe the bug**
Calling the terminal API with an array at "SaleToPOIRequest.PaymentRequest.PaymentTransaction.TransactionConditions.ForceEntryMode" fails.

From the small digging I did i seems like the types are warpped in an extra array in the following files.
lib\src\typings\terminal\cardAcquisitionTransaction.d.ts
lib\src\typings\terminal\cardReaderInitRequest.d.ts
lib\src\typings\terminal\transactionConditions.d.ts

It should be `Array<TransactionConditions.ForceEntryModeEnum>`and not `Array<Array<TransactionConditions.ForceEntryModeEnum>>`

**To Reproduce**
1. Create a SaleToPOIRequest containing "SaleToPOIRequest.PaymentRequest.PaymentTransaction.TransactionConditions.ForceEntryMode".
2. Set ForceEntryMode to an array of strings (as per documentation).
3. Request fail

**Expected behavior**
I expect the request to complete

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Node Version: 14.16.0
 - NPM Version: 6.14.11

**Additional context**

**Comment by jillingk** [comment]
Hi @Meisolsson,

Closing this issue as your PR is merged. Thanks again for the contribution! 

Best, Jilling 
Adyen
