### ISSUE TITLE
[BUG] Missing Action data in PaymentDetailsResponse class

### ISSUE THREAD

**Issue by dasanorct** [Adyen/adyen-node-api-library#1234]
**Describe the bug**
When using the API only mode and trying to pay with this credit card (4917 6100 0000 0000) the expected scenario is:
1. submit payment -> IdentifyShopper response
2. trigger fingerprint and send result -> ChallengeShopper response
3. trigger challenge and send result -> payment authorized

When calling to /v70/payments/details through `PaymentsApi.paymentsDetails()` the response expected is a `Promise<PaymentDetailsResponse>` so when converting your "ChallengeShopper" response, the action data is missing because the PaymentDetailsResponse does not have that attribute.

**Expected behavior**
Action information is mapped to the PaymentDetailsResponse object

**Comment by jillingk** [comment]
Hi @dasanorct,

Thanks for reaching out with your issue and apologies for the not so timely response. What library version are you using? And could you share your raw response you get from the `paymentsDetails()` call maybe? That would help a lot in order to find out the underlying issue.  

Best, Jilling
Adyen

**Comment by dasanorct** [comment]
Hi @jillingk,

I'm using the version 14.0.0. 

To simplify, where I run something like this: ` new CheckoutAPI(cfg).PaymentsApi.paymentsDetails(paymentDetailsData)`
with a payload like:
```
{
   "details" : {
      "threeds2.fingerprint" : "eyJ0aHJlZURTQ29tcEluZCI6IlkifQ=="
   },
   "paymentData" : "***...(12)"
}
```

This is calling your method:
```
public async paymentsDetails(paymentDetailsRequest: PaymentDetailsRequest, requestOptions?: IRequest.Options): Promise<PaymentDetailsResponse> {
        const endpoint = `${this.baseUrl}/payments/details`;
        const resource = new Resource(this, endpoint);
        const request: PaymentDetailsRequest = ObjectSerializer.serialize(paymentDetailsRequest, "PaymentDetailsRequest");
        const response = await getJsonResponse<PaymentDetailsRequest, PaymentDetailsResponse>(
            resource,
            request,
            { ...requestOptions, method: "POST" }
        );
        return ObjectSerializer.deserialize(response, "PaymentDetailsResponse");
    }
```

When debugging the `response` I get something like:
```
{
   "resultCode" : "ChallengeShopper",
   "action" : {
      "paymentData" : "***...(13)",
      "paymentMethodType" : "scheme",
      "authorisationToken" : "a token",
      "subtype" : "challenge",
      "token" : "***...(11)",
      "type" : "threeDS2"
   }
}
```
 But then, as you do `ObjectSerializer.deserialize(response, "PaymentDetailsResponse")` and try to convert the response to a `PaymentDetailsResponse` instance and as per [definition](PaymentDetailsResponse) you don't have the `action` field defined for that class, that information is lost.
 
Hope this helps you to understand the problem and let me know if this is a bug or I'm doing something wrong.
Thanks!

**Comment by dasanorct** [comment]
Hi @jillingk,

any update on this?

**Comment by wboereboom** [comment]
Hi @dasanorct,

Picking this up for @jillingk!
as you can see in our [API documentation](https://docs.adyen.com/api-explorer/Checkout/71/post/payments/details#responses-200), the action is not part of our PaymentsDetails Response model.
As you do report receiving this object, I'll forward this issue to one of our internal teams so they can address this inconsistency accordingly.

I apologise again for the delay, and for any inconvenience this might've caused you.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @dasanorct ,

another update;
You are likely getting this action object back to your merchant account configuration. 

Our support department can fix this for you. Please reach out to a support agent in order to get this resolved.

Kind Regards,
Wouter
Adyen

**Comment by dasanorct** [comment]
Hi @wboereboom,

In the documentation, a possible resultCode is "ChallengeShopper". If this is returned then I get another field "action" with the details which currently we are missing.

Unless something was changed, this scenario is a consequence of going through the 3DS then getting an answer from Adyen for presenting the fingerprint challenge, after presenting the running that challenge the result is sent to Adyen to /payment/details an the resultCode of the response is "ChallengeShopper". Then for challenging the shopper I need some details which should be included but they are not. Is not valid anymore the scenario I mentioned?

this was working fine with v13.1.3.

**Comment by wboereboom** [comment]
Hi @dasanorct,

Our support department indeed mentioned this scenario only happens for specific account configurations. I don't know how your account got configured that way, but our support department should be able to help you out with that so you can integrate your 3DS flow fully using the library.

Kind Regards,
Wouter
Adyen
