### ISSUE TITLE
[BUG] Websites guide is showing wrong documentation 

### ISSUE THREAD

**Issue by callumhemming** [Adyen/adyen-node-api-library#1274]
**Describe the bug**

Hope this is the correct place to report this. 
The getting started docs on the [website](https://docs.adyen.com/online-payments/build-your-integration/?programming_language=js&platform=Web&integration=Drop-in&version=5.51.0&tab=node_js_6) are out of sync with the README.

**On the website** (Web > Drop In > NodeJs > Using the library) the payment endpoint is accessed like so: CheckoutApi.payments(paymentRequest)

**But in the README**, it's checkoutApi.PaymentsApi.payments(paymentRequest), which is correct.

Following the guide on the website will cause an error.

Should save future new users some debugging time when fixed :)

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]
 - Node Version: [e.g. 8.1.2]
 - NPM Version: [e.g. 6.7]

**Additional context**

**Comment by Aleffio** [comment]
Hi @callumhemming, 
thanks a lot for raising this issue!
The docs have been corrected last week so we can close this issue,
please feel free to re-open it if you see other issues in our examples!

Best regards,
Alessio
Adyen
