### ISSUE TITLE
[BUG] @adyen/api-library v15.1.0 not available in npmjs.com registry

### ISSUE THREAD

**Issue by tpater** [Adyen/adyen-node-api-library#1295]
**Describe the bug**
When I try to install latest stable release with `npm install --save @adyen/api-library` I'm getting older version.

**To Reproduce**
```
npm show @adyen/api-library versions
[
  '1.0.0',        '1.0.1',      '1.1.0',       '1.1.1',
  '2.0.0',        '2.1.0',      '2.1.1',       '2.1.2',
  '2.1.3',        '2.1.4',      '2.1.5',       '2.1.6',
  '2.1.7',        '2.1.8',      '2.2.0',       '2.2.1-rc.0',
  '2.2.1-rc.1',   '2.2.1-rc.2', '2.2.1-rc.3',  '2.2.1-rc.4',
  '2.2.1',        '3.0.1-rc.0', '3.1.0',       '3.1.1',
  '3.1.2',        '3.1.3-rc0',  '3.1.3-rc1',   '3.1.3',
  '3.2.3',        '3.2.4',      '4.0.0',       '4.0.1',
  '4.0.2',        '4.0.3',      '5.0.0',       '5.0.1',
  '5.0.2-beta.0', '6.0.0',      '6.0.1',       '6.0.2',
  '6.0.3',        '7.0.0',      '8.0.0',       '8.1.0',
  '8.1.1',        '8.2.0',      '9.0.0',       '9.1.0',
  '10.0.0',       '10.1.0',     '10.2.0',      '10.3.0',
  '11.0.0',       '12.0.0',     '12.1.0',      '12.2.0',
  '13.0.0',       '13.1.0',     '13.1.1',      '13.1.2',
  '13.1.3',       '14.0.0',     '14.1.0',      '14.2.0',
  '14.3.0',       '14.4.0',     '15.0.0-beta'
]
```

**Expected behavior**
`npm` should fetch latest stable version consistent with latest tag and release in the gihub repository.
Expected `package.json` dependencies:
```
"dependencies": {
    "@adyen/api-library": "^15.1.0"
}
```    

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 23H2
 - Node Version: 18.17.0
 - NPM Version: 9.6.7

**Comment by kpiskadlo** [comment]
Is there any information that this version will soon be available as a public npm package?

**Comment by wboereboom** [comment]
Hi @tpater, @kpiskadlo,

Seems we have run into some issues with our GitHub Secrets.
We'll sort it out and backfill our NPM repo. Thanks for noticing these omissions.
Apologies for any issues and delays this might have caused on your end.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @tpater,

We got around to fixing this issue! Again; sorry for the inconvenience.
Thanks for reaching out about this everyone, we really appreciate the feedback and warnings.

Kind Regards,
Wouter
Adyen
