### ISSUE TITLE
ClientInterface is not respected. Unable to provide `www-authenticate` header in `requestOptions`

### ISSUE THREAD

**Issue by flow-danny** [Adyen/adyen-node-api-library#1331]
For some requests, such as `TransfersAPI.transferFunds` an additional `WWW-Authenticate` header must be passed in, but the default Client as shipped with the library makes this impossible, as it overwrites all `requestOptions.headers`:

https://github.com/Adyen/adyen-node-api-library/blame/f9dd227c151b7a0a4c20f192b783bb61c879142c/src/httpClient/httpURLConnectionClient.ts#L46

I suggest changing this line to:

```js
requestOptions.headers ??= {};
```

**Comment by DjoykeAbyah** [comment]
Hi @flow-danny!

Thank you for bringing this to our attention, this should indeed not happen. We've implemented your suggestion and you can expect this change in the upcoming library release!

Kind regards,

Djoyke
Adyen
