### ISSUE TITLE
[BUG] Unexpected mandatory issuer in iDEAL details

### ISSUE THREAD

**Issue by dicearr** [Adyen/adyen-node-api-library#1367]
**Describe the bug**

When using the checkout API to create an iDEAL payment, the issuer is mandatory: https://github.com/Adyen/adyen-node-api-library/blob/7c0c9ad18b84f2fca5f6be7967f9f862f216dcbc/src/typings/checkout/idealDetails.ts#L19

However, as per the code snippet given in the documentation (https://docs.adyen.com/payment-methods/ideal/api-only/#make-payment) seems like it should be optional.

**Expected behavior**

I'd expect documentation and typings to be aligned.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 20.12.2
 - NPM Version: 10.5.0
 
**Additional context**
 - @adyen/api-library version: 16.2.0 & 17.2.0

**Comment by wboereboom** [comment]
Resolved in #1370
