### ISSUE TITLE
[BUG] starting a transaction of paymentMethod.type: "afterpay_default" is not possible due to a mismatch between the required payload and the PaymentRequest type 

### ISSUE THREAD

**Issue by pvaneveld** [Adyen/adyen-node-api-library#1379]
**Describe the bug**
starting a transaction of `paymentMethod.type: "afterpay_default"` is not possible due to a mismatch between the required payload - which should contain `shopperName.gender` - and the `PaymentRequest` type - which does not contain `shopperName.gender`

**To Reproduce**
- start a transaction (`PaymentsApi.payments`) of `paymentMethod.type: "afterpay_default"` using `"@adyen/api-library": "18.1.0",`
- use a payload compatible with the `PaymentRequestType`, containing all the fields required for this payment method type. See the payload below as a reference

```
{
      "amount": {
        "currency": "EUR",
        "value": 798
      },
      "shopperIP": "someip",
      "merchantAccount": "account",
      "merchantOrderReference": "some-reference",
      "paymentMethod": {
        "type": "afterpay_default"
      },
      "reference": "reference",
      "returnUrl": "https://returnurl.nl/url",
      "storePaymentMethod": false,
      "lineItems": [
        {
          "sku": "someSKU",
          "description": "socks",
          "quantity": 1,
          "taxPercentage": 0.21,
          "amountIncludingTax": 299,
          "amountExcludingTax": 247,
          "taxAmount": 52,
          "productUrl": "https://www.image.nl/image.jpg"
        }
      ],
      "shopperLocale": "nl_NL",
      "shopperName": {
        "firstName": "John",
        "lastName": "Doe"
      },
      "billingAddress": {
        "country": "NL",
        "city": "Amsterdam",
        "street": "Fazantenweg",
        "houseNumberOrName": "1",
        "postalCode": "1021 HM"
      },
      "deliveryAddress": {
        "country": "NL",
        "city": "Amsterdam",
        "street": "Fazantenweg",
        "houseNumberOrName": "1",
        "postalCode": "1021 HM"
      },
      "telephoneNumber": "+31652336011",
      "shopperEmail": "john@doe.nl",
      "countryCode": "NL",
      "shopperReference": "somereference",
      "deviceFingerprint": "fingerprint",
      "dateOfBirth": "1978-05-04T22:00:00.000Z"
}
```
- the request will result in the following error

```
HTTP Exception: 422. : Required field 'shopperName.gender' is not provided."
```
- even when gender is included in the `shoperName` object, e.g. `gender: "MALE"`, the same issue occurs.
- submitting a similar payload via curl actually creates a transaction, indicating a problem in the library

**Expected behavior**

- a payload that matches the `PaymentRequest` type does not result in errors about fields that are not present in this type.

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Node Version: [20.9.0]
 - PNPM  Version: [9.4.0]

**Comment by jillingk** [comment]
Hi @pvaneveld,

Thanks for reaching out here and apologies for the delayed answer. Seems this field is missing from the library, I'm following up to fix this asap. 

Best, Jilling
Adyen
