### ISSUE TITLE
[BUG] Feedback for is not open to public

### ISSUE THREAD

**Issue by kristofferse** [Adyen/adyen-node-api-library#1435]
**Describe the bug**
The [feedback form](https://forms.gle/A4EERrR6CWgKWe5r9) listed in the README is restricted to only be available to users in the Adyen organisation.

**To Reproduce**
Visit the link: https://forms.gle/A4EERrR6CWgKWe5r9

**Expected behavior**
Access feedback form even if not part of Adyen organisation.

**Comment by jillingk** [comment]
Hi @kristofferse,

Thanks for catching this! We changed the permissions for the form being accessible outside of the organisation. Looking forward to hearing your feedback!

Best, Jilling
Adyen
