### ISSUE TITLE
[BUG] Unexpected undefined return value for a refund

### ISSUE THREAD

**Issue by splacentino** [Adyen/adyen-node-api-library#633]
**Describe the bug**
When performing a `refund` using `modification API`, call should return a promise as define in type:

```ts
refund(refundRequest: GenericRequest<IPayments.ModificationRequest>, requestOptions?: IRequest.Options): Promise<IPayments.ModificationResult>;
```

But I got a Promise resolved with `undefined` instead of an exception or a result.

```
TypeError: Cannot destructure property 'pspReference' of 'undefined' as it is undefined. 
```

**To Reproduce**
```ts
const modification = new Modification(client);

 const { response, pspReference } = await modification.refund({
    merchantAccount: "mymerchant",
    originalReference: "mytransaction",
    modificationAmount: {
      currency: "EUR",
      value: 324
    }
  });
```

**Expected behavior**
An exception to be raised or `response` to have an error value.

**Desktop (please complete the following information):**

 - Node Version: 15.1
 - NPM Version: 7.0.8
 - Adyen: 5.0.1 & 6.0.3

**Comment by splacentino** [comment]
Any news ?

cheers

**Comment by wboereboom** [comment]
Hi @splacentino,
I ran some tests, and I have not been able to reproduce this issue on the 8.0.0 version of the library.
let me know if this issue still persists for you on this version of the library
