### ISSUE TITLE
Update to APIv66 as dependency of adyen-web

### ISSUE THREAD

**Issue by tniemann** [Adyen/adyen-node-api-library#636]
Hi,

Another 2,5 month passed by and still no updates for the node SDK!

https://github.com/Adyen/adyen-node-api-library/releases

I can not update the web SDK cause of the dependency of the API Version 66. 
But the web SDK has a lot of updates and fixes.

https://github.com/Adyen/adyen-web/releases

Almost every week a new update.

When will the node SDK will be updated?

Thx in advanced.

**Comment by peterojo** [comment]
Hi @tniemann we have released an updated version for the new version of Checkout API.
