### ISSUE TITLE
[BUG] Could not call Terminal API LIVE

### ISSUE THREAD

**Issue by nam-truong-le** [Adyen/adyen-node-api-library#649]
I guess you forget to set the LIVE Terminal API URL, you only do it for [TEST](https://github.com/Adyen/adyen-node-api-library/blob/b671d126ac1a212d3c1fcccd7454481efff82caf/src/client.ts#L109)

**Describe the bug**
Could not call Terminal API LIVE

**To Reproduce**
Activate LIVE

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wboereboom** [comment]
Thank you for reporting this issue!  
I've added the LIVE endpoint to the setEnvironment method in the Client class.
