### ISSUE TITLE
[PW-4426] Support for Checkout API v67

### ISSUE THREAD

**Issue by tooga** [Adyen/adyen-node-api-library#652]
**Is your feature request related to a problem? Please describe.**

Hi, there are many new Web component and 3D Secure 2 updates that requires Checkout API v67 for them to work. It's currently blocking our development, since we cannot use those if using this package. Any timeline when v67 would be supported by this library?

Thanks!

**Comment by carly-cloud** [comment]
I don't understand why it always takes months to get this library updated to the latest API version. There is a dependency between this library and the web library and we always have to wait to get the latest fixes and feature just because this library does not get updated on time.

**Comment by nicogies** [comment]
Hello, same here, we are blocked because on **Febuary 25th** was released Web Components 4.0.0 that requires Checkout API v67 or later.

**Comment by wboereboom** [comment]
Hi Everyone,
Thank you all for raising this issue.
We are currently working on upgrading the library to support v67 of the checkout API.
I'll make sure to update this issue  and let you all know when we get there.

Thank you for your patience, and apologies for the delay.

**Comment by wboereboom** [comment]
Version 8.0.0 with checkout api v67 support is now available from either the repository or NPM.
