### ISSUE TITLE
[BUG] additionalData.allow3DS2 type should be a boolean

### ISSUE THREAD

**Issue by Romsters** [Adyen/adyen-node-api-library#662]
**Describe the bug**
In v67 `POST /payments` request parameters there is `additionalData (AdditionalData3DSecure).allow3DS2`. This has a string type in the API Explorer and in the code here https://github.com/Adyen/adyen-node-api-library/blob/54edffa5e3f426c3c536dca9fe2de34829087e48/src/typings/checkout.ts#L184.
Shouldn't it be just a boolean?

**Expected behavior**
AdditionalData3DSecure.allow3DS2 is a boolean.

**Comment by wboereboom** [comment]
Hi @Romsters,
Thank you for your bug report.
All types in this repository are generated based on the Adyen API. Hence this issue cannot be resolved through any changes on this repository alone.
Please open a ticket [here](https://github.com/Adyen/adyen-openapi/issues) to report any inconsistencies or omissions on the API definitions.
If and when these changes get made, this library will be updated to correspond to the updated API request and response objects
