### ISSUE TITLE
[BUG] Platforms ENDPOINT does not work

### ISSUE THREAD

**Issue by AlbertoGuillermoH** [Adyen/adyen-node-api-library#666]
**Description**
There is a problem with the end point of platforms. Can't find any function

**To Reproduce**

...
const endPoints = require('@adyen/api-library')
export const platform = new endPoints.Platforms(client)
...
const response = await **platform.createAccountHolder**({
				...req.body
})

Error: index_1.platform.createAccountHolder is not a function, error code: undefined
(node:43372) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
...
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43372) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:43372) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
...

**Expected behavior**
The correct callback

**Desktop (please complete the following information):**
 - OS:  Mac
 - Node Version: v14.15.4
 - NPM Version: 6.14.10

**Comment by wboereboom** [comment]
Hi @AlbertoGuillermoH ,

Thank you for raising this issue.
Unfortunately, I am currently unable to reproduce your error.
Do you have a more detailed stack trace so I can see what lines are causing this error?
Are you running the library from a browser? Or are you using it in a backend system?

**Comment by AlbertoGuillermoH** [comment]
Hello good afternoon, sorry about the delay.

I am using a backend by using Express and Node to connect to the api.

The problem occurs when I try to access any method of Platforms.

Here are the lines of code and the error message:

Error: index_1.platforms.createAccountHolder is not a function, error code: undefined
(node:2317) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:255:11)
    at ServerResponse.writeHead (/Users/akimadaccount/Documents/GUBICK/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/Users/akimadaccount/Documents/GUBICK/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:246:8)
    at write_ (_http_outgoing.js:685:9)
    at ServerResponse.write (_http_outgoing.js:661:15)
    at writetop (/Users/akimadaccount/Documents/GUBICK/node_modules/express-session/index.js:291:26)
    at ServerResponse.end (/Users/akimadaccount/Documents/GUBICK/node_modules/express-session/index.js:352:16)
    at ServerResponse.send (/Users/akimadaccount/Documents/GUBICK/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/Users/akimadaccount/Documents/GUBICK/node_modules/express/lib/response.js:267:15)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2317) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2317) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:255:11)
    at ServerResponse.writeHead (/Users/akimadaccount/Documents/GUBICK/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/Users/akimadaccount/Documents/GUBICK/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:246:8)
    at write_ (_http_outgoing.js:685:9)
    at ServerResponse.end (_http_outgoing.js:798:5)
    at writeend (/Users/akimadaccount/Documents/GUBICK/node_modules/express-session/index.js:262:22)
    at ontouch (/Users/akimadaccount/Documents/GUBICK/node_modules/express-session/index.js:349:11)
    at /Users/akimadaccount/Documents/GUBICK/node_modules/connect-typeorm/src/app/TypeormStore/TypeormStore.ts:198:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2317) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

The call to the api is made as follows:

```
const {Client, Config,Platforms} = require ('@adyen / api-library')

export const config = new Config ()
export const client = new Client ({config})
export const platforms = new Platforms (client)

const response = await platforms.createAccountHolder ({
... req.body
})
```

where req.body is the corresponding data

Thank you!

All the best,

Alberto

**Comment by AlbertoGuillermoH** [comment]
I don't know if this has something to do with it ... Could it be that the endpoint is wrong? **https://cal-test.adyen.com/cal/services/Account/v6//closeAccount**
```

<ref *1> Platforms {
  apiKeyRequired: false,
  client: Client {
    config: Config {
      apiKey: '***',
      merchantAccount: '***',
      endpoint: 'https://pal-test.adyen.com',
      marketPayEndpoint: 'https://cal-test.adyen.com/cal/services',
      hppEndpoint: 'https://test.adyen.com/hpp',
      _checkoutEndpoint: 'https://checkout-test.adyen.com/checkout',
      terminalApiCloudEndpoint: 'https://terminal-api-test.adyen.com'
    },
    _httpClient: HttpURLConnectionClient {}
  },
  createRequest: [Function (anonymous)],
  _closeAccount: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//closeAccount'
  },
  _updateAccount: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//updateAccount'
  },
  _createAccount: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//createAccount'
  },
  _uploadDocument: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//uploadDocument'
  },
  _getUploadedDocuments: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//getUploadedDocuments'
  },
  _deleteBankAccounts: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//deleteBankAccounts'
  },
  _deletePayoutMethods: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//deletePayoutMethods'
  },
  _deleteShareholders: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//deleteShareholders'
  },
  _checkAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//checkAccountHolder'
  },
  _createAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//createAccountHolder'
  },
  _getAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//getAccountHolder'
  },
  _updateAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//updateAccountHolder'
  },
  _updateAccountHolderState: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//updateAccountHolderState'
  },
  _suspendAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//suspendAccountHolder'
  },
  _unSuspendAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//unSuspendAccountHolder'
  },
  _closeAccountHolder: PlatformsAccount {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Account/v6//closeAccountHolder'
  },
  _accountHolderBalance: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//accountHolderBalance'
  },
  _accountHolderTransactionList: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//accountHolderTransactionList'
  },
  _payoutAccountHolder: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//payoutAccountHolder'
  },
  _transferFunds: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//transferFunds'
  },
  _refundFundsTransfer: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//refundFundsTransfer'
  },
  _setupBeneficiary: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//setupBeneficiary'
  },
  _refundNotPaidOutTransfers: PlatformsFund {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Fund/v6//refundNotPaidOutTransfers'
  },
  _getOnboardingUrl: PlatformsHostedOnboardingPage {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Hop/v6//getOnboardingUrl'
  },
  _createNotificationConfiguration: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//createNotificationConfiguration'
  },
  _getNotificationConfiguration: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//getNotificationConfiguration'
  },
  _getNotificationConfigurationList: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//getNotificationConfigurationList'
  },
  _testNotificationConfiguration: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//testNotificationConfiguration'
  },
  _updateNotificationConfiguration: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//updateNotificationConfiguration'
  },
  _deleteNotificationConfiguration: PlatformsNotificationConfiguration {
    service: [Circular *1],
    endpoint: 'https://cal-test.adyen.com/cal/services/Notification/v6//deleteNotificationConfigurations'
  }
}
```

**Comment by wboereboom** [comment]
Hi @AlbertoGuillermoH,

I noticed you are calling 
`platforms.createAccountHolder`

This function only exists in the `Account` subclass of the platforms object.
Could you try this:
`platforms.Account.createAccountHolder`.

Hope that helps!
Let me know if your issue persists.

Happy coding!
Wouter
Adyen

**Comment by AlbertoGuillermoH** [comment]
It was just that. Everything solved, thank you very much !!
