### ISSUE TITLE
[BUG] wrong case in NotificationItem.notificationRequestItem

### ISSUE THREAD

**Issue by belinde** [Adyen/adyen-node-api-library#687]
**Describe the bug**
The class NotificationItem has the property notificationRequestItem but the actual payload from a JSON notification has NotificationRequestItem (first letter uppercase). In a Typescript project 

**To Reproduce**
```
import { hmacValidator } from '@adyen/api-library';
import { Notification } from '@adyen/api-library/lib/src/typings/notification/notification';

const notification: Notification = JSON.parse(JSON_STRING_FROM_THE_BODY);
const notificationItem = notification.notificationItems[0]

const validator = new hmacValidator();
validator.validateHMAC(notificationItem.notificationRequestItem, HMAC)
```
This code will fail with `TypeError: Cannot read property 'additionalData' of undefined`. Changing the first letter to uppercase will result in the compiler complaining `Property 'NotificationRequestItem' does not exist on type 'NotificationItem'. Did you mean 'notificationRequestItem'?`. As a workaround, the array notation can be used:

```
notificationItem['NotificationRequestItem']
``` 

**Expected behavior**
The type Notification should reflect the API result

**Desktop (please complete the following information):**
 - OS: Linux
 - Node Version: 16.0.0
 - NPM Version: 7.11.22

**Comment by wboereboom** [comment]
Hi @belinde,
Thank you for bringing this under our attention.

Our type generator does not seem to like field names that start with  capital letters, so that's probably what caused the problem you encountered as well.
I'll look into this + fix your issue in the process. 
Keep an eye on this thread for updates.
