### ISSUE TITLE
How to create Accounts with SDK. I got  401

### ISSUE THREAD

**Issue by GNURub** [Adyen/adyen-node-api-library#725]
When I use Platforms objecto I got 401. Some example to use it?.

	  const client = new Client({
	    environment: 'TEST',
	    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxx',
	  });
	  const platforms = new Platforms(client);
	  const checkout = new CheckoutAPI(client);
	  
	  // I get 401 error
	  platforms.Account.createAccountHolder({xxxxx}).then(console.log);

	  // Works!
	  checkout.paymentMethods({
		    channel: "Web",
		    merchantAccount: process.env.MERCHANT_ACCOUNT,
	  }).then(console.log);

**Comment by wboereboom** [comment]
Hi @GNURub,

Thank you for raising this issue.
We are hearing your concerns about the documentation of the API Libraries and we have plans to improve that in the future.
For now, it seems like you get an 'Unauthorised' response back from our API.
Can you please check whether you have the right Role to perform this action? 
https://docs.adyen.com/account/user-roles#page-introduction

Details on what the request should look like can be found here:
https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder

Hope this helps you continue your development for now.

Kind regards,
Wouter
Adyen

**Comment by GNURub** [comment]
1. I created a new user (admin) with all Roles asigned (/Account/Users).
2. I login with new user in test environment.
3. I create new API crential with all Roles asigned, and generate new API KEY.
4. Then I use 'adyen-node-api-library' in my app:
		
		    import { Client, Platforms } from '@adyen/api-library';
		    const client = new Client({
		    	environment: 'TEST',
		    	apiKey: '<API_KEY_GENERATED_STEP_3>',
		    });
			const platforms = new Platforms(client);
			platforms.Account.createAccountHolder({
		      accountHolderCode: 'q6ub3f877m7eaq8e',
		      accountHolderDetails: {
		        email: 'ruben@test.com',
		        individualDetails: {
		          name: {
		            firstName: 'Ruben',
		            lastName: 'test',
		          },
		        },
		        address: {
		          country: 'ES',
		        },
		      },
		      legalEntity: 'Individual',
		    }).then((e) => {
		      console.log(e);
		    });



		


		    curl https://cal-test.adyen.com/cal/services/Account/v6/createAccountHolder \
		    -H "x-API-key: YOUR_X-API-KEY" \
		    -H "content-type: application/json" \
		    -d '{
		      | "accountHolderCode":"TestAccountHolder5691",
		      | "accountHolderDetails":{
		      | "address": {
		      | "country": "US"
		      | },
		      | "email":"test@adyen.com",
		      | "individualDetails":{
		      | "name":{
		      | "firstName":"First name",
		      | "gender":"MALE",
		      | "lastName":"Last Name"
		      | }
		      | }
		      | },
		      | "createDefaultAccount":true,
		      | "legalEntity":"Individual"
		      | }'

**Comment by wboereboom** [comment]
Hi @GNURub ,

I have tried and reproduced the issue you are experiencing.
Most likely the API key you are using is the one created for regular payments.
Can you confirm the API key you are using is for an account called `ws_[123456]@MarketPlace.[YourPlatformAccount]` and not ` ws@Company.[YourCompanyAccount]` as described in the quick-start link I posted above?
