### ISSUE TITLE
NotificationItem property naming bug

### ISSUE THREAD

**Issue by straimis** [Adyen/adyen-node-api-library#740]
**Describe the bug**
There is a mismatch in **_NotificationItem_** type. Instead of **NotificationRequestItem** property name there is a name in pascalCase - **notificationRequestItem**. 
That's not right according to the documentation and implementation https://docs.adyen.com/development-resources/webhooks/understand-notifications

**To Reproduce**
With the latest version @adyen/api-library:9.0.0, screenshot attached - you can see a mismatch in the property name.

**Expected behavior**
**_NotificationItem_** must have a property named **_NotificationRequestItem_** instead of **_notificationRequestItem_**

**Screenshots**
![image](https://user-images.githubusercontent.com/148342/130578324-02f66a0d-dfbc-493a-bf19-97a92f1fe25c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 14.17.5
 - NPM Version: 6.14.13

**Comment by wboereboom** [comment]
Hello @straimis,

Thanks for raising this issue!
This bug was introduced by our type generator not respecting capitalized field names.
I will update the types accordingly.

Kind regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Hi @straimis,

This issue is fixed in the latest release of the library (9.1.0).

Regards,
Wouter
Adyen
