### ISSUE TITLE
[FEATURE] Add documentation for TypeScript usage

### ISSUE THREAD

**Issue by mjeri** [Adyen/adyen-node-api-library#761]
**Is your feature request related to a problem? Please describe.**

It's hard to understand the correct usage of the client library without having examples or documentation. Only pointing to the API documentation is not helping so much.

I stumbled over this once again as I upgraded the library over many versions (3.2.3 -> 9.0.0) and now I'm puzzled as the `ICheckout` namespace seems to be gone and I'm having many import statements. This may be fine, but I'm not sure if I use the client in the right way. A missing TS example + documentation make it hard for me to say if it's the case.

This is how my imports look like now:

```
import { PaymentResponse } from '@adyen/api-library/lib/src/typings/checkout/paymentResponse';
import { StoredPaymentMethod } from '@adyen/api-library/lib/src/typings/checkout/storedPaymentMethod';
import { PaymentMethodsResponse } from '@adyen/api-library/lib/src/typings/checkout/paymentMethodsResponse';
import { PaymentRequest } from '@adyen/api-library/lib/src/typings/checkout/paymentRequest';
```

Is this the canonical usage?

**Describe the solution you'd like**

Have an example project or documentation page showing a basic TypeScript implementation.

**Describe alternatives you've considered**

LMK when I can provide you more here?

**Additional context**

Thank you for creating the client library!

**Comment by wboereboom** [comment]
Hi @mjeri,

Thank you for raising this issue. We are aware of the shortcomings of our API documentation, and are actively working on improving them.
The issue you raised adds to our belief that there is room for improvement here.

The way you are currently importing your types is correct, but we are working on improving that as well.
In the future you will be able to do something along the lines of this:
`import {Types} from "@adyen/api-library"; ` so you can get your types like so :`Types.checkout.PaymentMethodsRequest`.
See #755 for a full example and the progress on this feature.
This is not likely to break the way you are declaring the imports right now.

For now I regret to inform you that we do not have an accurate timeline on the improved documentation yet.

Kind regards,
Wouter
Adyen
