### ISSUE TITLE
[BUG] Types of platforms notifications are not exported in the new version

### ISSUE THREAD

**Issue by VincentvD** [Adyen/adyen-node-api-library#783]
**Describe the bug**
I'm using `IPlatformsNotifications.AccountHolderCreateNotification` and other platforms notifications,  and it seems that these types of notifications are not exported in the latest version of this library. This gives conflicts on for example the  `KYCVerificationResult` and `KYCVerificationResult2` types.

**To Reproduce**
A bit much to create a concise example but try using the platformsAccount notification types with this latest version. You'll run into typing errors.

**Expected behavior**
I expect all types to be exported via the new `Types`.

**Comment by wboereboom** [comment]
Hi @VincentvD,
Thanks for raising this issue.
We are currently working on changing our type generation from the old interfaces to the exported typings.
I'll add the migration of the plaforms notifications to our planning. 

Kind regards,
Wouter,
Adyen

**Comment by wboereboom** [comment]
Closing this issue, Fix is included in version 10.1.0
