### ISSUE TITLE
[BUG] AdditionalData lacks the field paymentLinkId

### ISSUE THREAD

**Issue by SergioBergaminiCodeploy** [Adyen/adyen-node-api-library#787]
**Describe the bug**
As far as I understand the APIs implementation by reading issue #494, to deserialize a webhook notification the class `NotificationRequest` must be used. So far so good. For this kind of deserialization to work, each field must be manually mapped which is of course a process prone to errors.

For example, the class `AdditionalData` lacks the field `paymentLinkId` which is quite important and should be there based on the documentation (see https://docs.adyen.com/unified-commerce/pay-by-link/payment-links/api#notification).

**Comment by wboereboom** [comment]
I'm discussing internally how to deal with these fields missing in the spec. 
In the mean time we can review + merge this and include it in the upcoming release, which we will probably do somewhere this week.
