### ISSUE TITLE
[BUG] Terminal Sync `undefined` response.

### ISSUE THREAD

**Issue by NalinSajwan** [Adyen/adyen-node-api-library#838]
**Describe the bug**
No response received from Terminal sync api, when `SaleToPOIRequest > EventNotification` is sent as a reply.

**To Reproduce**
Disconnect the standalone device and send the request using `node library` and via `Postman`.
- Using `Postman` we clearly receive a response object with `SaleToPOIRequest > EventNotification`.
- Use `node library`, terminal sync function just returns `undefined`.

**Expected behavior**
We should either receive:
- `TerminalApiRequest` if response has `SaleToPOIRequest` key, or
- `TerminalApiResponse` if response receives `TerminalApiResponse`.

**Screenshots**
![image](https://user-images.githubusercontent.com/10107926/151266602-7bbf7143-c382-44c4-8d06-5f3873e3140e.png)

**Comment by wboereboom** [comment]
Hi @NalinSajwan ,
Thanks for raising this issue.
We are currently investigating what the fix should be.
It is likely a field is missing from the `TerminalApiResponse`. An API request should never return another API request object. Hence the solution you proposed cannot be accepted at this time.

Kind Regards,
Wouter
Adyen

**Comment by NalinSajwan** [comment]
@wboereboom This is the scenario when `sync` endpoint returns `SaleToPOIRequest > EventNotification` -
https://docs.adyen.com/point-of-sale/error-scenarios#terminal-unavailable

I was trying to generate this scenario using this module, and was getting `undefined` as a response (if terminal is unavailable).

Let me know if the fix seems fine for this scenario.

**Comment by wboereboom** [comment]
@NalinSajwan  Thanks for that elaboration!
The right course of action would then be to include `SaleToPOIRequest to the `TerminalApiResonse` model.

I'm running it past our POS experts now.

Kind Regards,
Wouter
Adyen

**Comment by NalinSajwan** [comment]
@wboereboom Cool, let me know if you guys are planning fix internally (if required in other places as well).

Or else I can raise it for sync api at-least (which I am using for now).

**Comment by wboereboom** [comment]
@NalinSajwan , yes we are planning to fix it. Most likely we will update the definition of the `TerminalApiResponse` to include an optional `SaleToPOIRequest` (so it can return both the `SaleToPOIRequest` and the `SaleToPOIResponse`).

That would most likely fix your issue if I have understood it correctly, right?

**Comment by NalinSajwan** [comment]
> @NalinSajwan , yes we are planning to fix it. Most likely we will update the definition of the `TerminalApiResponse` to include an optional `SaleToPOIRequest` (so it can return both the `SaleToPOIRequest` and the `SaleToPOIResponse`).
> 
> That would most likely fix your issue if I understand correctly, right?

@wboereboom Yeah, that should solve the issue.

**Comment by NalinSajwan** [comment]
Hey @wboereboom, I see that you guys have merged the fix. Any reasons for delay in releasing the new version on NPM ?

**Comment by wboereboom** [comment]
HI @NalinSajwan,
The Pull request for the release is still under review by my team. 
Once it's reviewed the new Library version will be released

**Comment by wboereboom** [comment]
This issue has been released in release v10.2.0
