### ISSUE TITLE
[BUG] MaskedPAN should be MaskedPan in typings for cardData

### ISSUE THREAD

**Issue by EoinFalconer** [Adyen/adyen-node-api-library#846]
**Describe the bug**
The returned data for card data in the typings is MaskedPAN in this library whereas the reality is MaskedPan. The changes needed are just in src/typings/terminal/cardData.ts

**To Reproduce**
Just import the library and try and use MaskedPan and you'll get TS errors.

**Expected behavior**
No TS errors and MaskedPan being typed.

**Additional context**
Love the typings in general so thank you for this! 💯

**Comment by wboereboom** [comment]
Hi @EoinFalconer,

Thank you for raising this issue.
I've double checked this in our API documentation and you're right!

I'm opening a PR to fix this.
Happy to hear you enjoy working with our library 🎉 .

Kind Regards,
Wouter
Adyen
