### ISSUE TITLE
[FEATURE] Type Display notification types in ReferenceID

### ISSUE THREAD

**Issue by EoinFalconer** [Adyen/adyen-node-api-library#850]
**Is your feature request related to a problem? Please describe.**
Hello again, sorry for the bugging but better to make a request than remain silent. At the moment `ReferenceID` for display notifications over the Terminal API webhooks (inside the parent type `TerminalApiRequest`) are not typed as per [the documentation](https://docs.adyen.com/point-of-sale/terminal-api-fundamentals/display-notifications).

**Describe the solution you'd like**
I would really love to have these available in an enum so that I don't have to write these typings myself when I use the library for everything else.

**Describe alternatives you've considered**
Just adding them myself and typing them all out.

**Additional context**
I'm aware that typing `ReferenceID` probably isn't the way forward as that is in a different format, but making available an enum of some description would make some better DX here :-) Again, thanks for the nice library! 💯

**Comment by wboereboom** [comment]
Hi @EoinFalconer,

Thanks again for raising this issue! 
No apologies necessary, we're always eager to hear what features our customers are missing in our libraries.
I'll discuss this issue internally and decide if we can honor your request. 
We try to generate the models in our libraries as much as possible, and unfortunately the terminal is giving us a hard time in that regard.
Still delivering a good developer experience is what the library is all about.
To be continued...

Kind Regards,
Wouter
Adyen

PS: Feel free to open a PR if you'd like to also contribute to this repo and implement the changes you want to see 🚀. If not; that's cool too, it just might take a little bit longer for us to get things implemented.
