### ISSUE TITLE
getTaxForm Endpoint

### ISSUE THREAD

**Issue by endbay** [Adyen/adyen-node-api-library#865]
Hi there,

I cannot find the /getTaxForm Endpoint. Referring to the docs it should be under Platforms Accounts but it seems like it has been forgotten?

https://docs.adyen.com/api-explorer/#/Account/v6/post/getTaxForm

Is there a workaround or will this endpoint be added in the next versions?

**Comment by wboereboom** [comment]
Hi @endbay,

We have not added this endpoint yet.
I've made a ticket on our end and will be working on its implementation shortly.
Up until that point I'm sorry to inform you I do not yet have a workaround. 
I do expect this to be implemented in a matter of days however.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
Added this in v10.3.0
