### ISSUE TITLE
[PW-6628][BUG] Key 'SalesData' is missing in 'ReversalRequest' class.

### ISSUE THREAD

**Issue by NalinSajwan** [Adyen/adyen-node-api-library#869]
**Describe the bug**
Key `SalesData` is missing in `ReversalRequest` class, which is used for partial refund (resulting in params to be skipped).

**To Reproduce**
To check actual request body for terminal sync we can use `httpClient`. In `json` body `SalesData` gets removed.

**Expected behaviour**
`SalesData` should not be removed from request payload.

**Screenshots**
- Typescript error: <img width="994" alt="image" src="https://user-images.githubusercontent.com/10107926/163055420-4d466a4f-bdc1-4944-a75d-0872c7a06984.png">
- [Partial refund payload](https://docs.adyen.com/point-of-sale/refund-payment/referenced?tab=partial_refund_2)  containing `SalesData` inside `ReversalRequest`.
- [`ReversalRequest` class](https://github.com/Adyen/adyen-node-api-library/blob/develop/src/typings/terminal/reversalRequest.ts#L41) not containing `SalesData`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 14.19.1
- NPM Version: 6.14.16

**Comment by AlexandrosMor** [comment]
Hello @NalinSajwan,

Indeed the `saledata` is missing from  `ReversalRequest`.  We created an internal ticket to add it and we are going to pick it up as soon as possible. Please feel free to open a pull request with that fix which could review it as it is always faster. Check our [contribution guide](https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/CONTRIBUTING.md)

kind regards,
Alexandros
Adyen
