### ISSUE TITLE
[PW-6832][BUG] Incorrect Date type for `CreateCheckoutSessionResponse` properties

### ISSUE THREAD

**Issue by bram-l** [Adyen/adyen-node-api-library#887]
**Describe the bug**
In various places throughout this library the `Date` is used as a type, while the client actually returns a string. For example when looking at the return type of the `sessions` function of the Checkout API, it looks like a Date object is returned for the `expiresAt` property, which is not the case.

**To Reproduce**
```ts
import { Client, Config, CheckoutAPI } from "@adyen/api-library"

const config = new Config({ ... });
const client = new Client({ config });

const response = await new CheckoutAPI(client).sessions({ ... });

console.log(typeof response.expiresAt);
// string

const expiresAt: string = response.expiresAt; // actual data 
// Error: Type 'Date' is not assignable to type 'string'. ts(2322)
```

**Expected behavior**
Either a Date object being returned, or the type to be corrected to `string`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: 14.19.2
 - NPM Version: 6.14.17

**Comment by jillingk** [comment]
Hi @bram-l,

Thanks a lot for raising this issue with us! It seems that with the new releases the models have been simplified somewhat leading to the Date objects not properly being parsed as such anymore. We're investigating how to correctly solve this for the library and will get back to you once we have found and implemented a good solution.

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @bram-l,

With the recent releases this issue has been solved so I'll be closing this ticket. If there is anything else I can help you with let me know.

Best, Jilling
Adyen
