### ISSUE TITLE
[BUG] [TEST ENV] Metadata can't be passed with SalesToAquirerData in TerminalApiRequest - sync

### ISSUE THREAD

**Issue by nx-c** [Adyen/adyen-node-api-library#950]
**Describe the bug**
Passing metadata in the SalesToAquirerData is removed by serializer due to type missing.

**To Reproduce**
Pass key value pairs in metadata field of SalesToAquirerData.

**Expected behavior**
Metadata is being send to and processed by the Adyen Plattform

**Screenshots**

**Desktop (please complete the following information):**
 - OS: docker container - node
 - Node Version: 14.19.1
 - NPM Version: 6.14.16

**Additional context**
I went through some previous issues and releases. Looks like the types for metadata where removed again after they where added previously.

I fixed it on my local machine, but not with much success. Even though I can send the metadata with the request and even get it back with the response. The platform(customer area) is not showing the metadata for POS payments. It seems like it's not passed to the actual payment creation.

**Comment by jillingk** [comment]
Hi @nx-cm

Thanks a lot for bringing this bug to our attention. After quickly taking a look it seemed like we were missing the attribute type map for the metadata. I fixed this just now! 

If there is anything else I can help you with, please do let me know.

Best, Jilling
Adyen
