### ISSUE TITLE
[FEATURE] Any plan to release a new version?

### ISSUE THREAD

**Issue by pepakriz** [Adyen/adyen-node-api-library#964]
**Is your feature request related to a problem? Please describe.**
I'd like to use new method calls like `captures`. They are already implemented in develop branch, but not in a stable release.

**Comment by wboereboom** [comment]
Hey @pepakriz,

Over the last few weeks we have invested heavily in making the library feature-complete.
Though we are not quite there yet, we are planning to make a new release in the upcoming two weeks.

Thanks for your patience. I hope the new release will contain the features you need to build your integration with Adyen.

Kind Regards,
Wouter
Adyen

**Comment by pepakriz** [comment]
@wboereboom Ok, thanks for sharing this time estimate.
